# The goal to send when requesting for help

# A header indicating the time of the assistance request
time stamp

# The component that created the request
string component

# The current actionlib_msgs/GoalStatus status of the component
uint8 component_status

# The priority of the request. Lower is higher. This does not guarantee that
# requests with a higher priority will be addressed immediately. That decision
# is up to the arbitrator based on other information in this goal message
# TODO: Perhaps this breakdown of priority classes should be driven by the
# literature
uint8 PRIORITY_CRITICAL=10
uint8 PRIORITY_IMPORTANT=20
uint8 PRIORITY_NORMAL=30
uint8 PRIORITY_INFO=40
uint8 priority

# The context of the status. This is a pickled byte array
string context
---
# The result after fulfilling the request

# The behavior after the request has been fulfilled. The implementation of these
# resumption behaviours is component dependent. The definitions of these hints
# are:
# - RESUME_NONE: the intervention has accomplished the goal that you set out to
#                       accomplish. Congratulations, you need to do nothing.
# - RESUME_CONTINUE: continue executing from the point of the error. something
#                       has intervened to rectify the problem.
# - RESUME_RETRY: retry the everything up until the point of the error. the
#                       blocker has been removed, but the environment has also
#                       reset itself as a result
# - RESUME_NEXT: skip the component that errored out and move on to the next
#                   one. assume that 'next' applies on the highest level
# - RESUME_PREVIOUS: rerun the component that was run before the one that
#                   errored out. assume that 'prev' applies on the highest level
uint8 RESUME_NONE=0
uint8 RESUME_CONTINUE=1
uint8 RESUME_RETRY=2
uint8 RESUME_NEXT=3
uint8 RESUME_PREVIOUS=4
uint8 resume_hint

# The context of the resumption. Just in case there are things the component
# should be aware of when the strategy finished. This is a pickled byte array
string context

# Statistics on the assistance
Statistics stats
---
# The feedback while the request is being fulfilled

# The name of the strategy that is currently fulfilling the request
string strategy
