tasks:
  # Setup for the main tasks. Can get rid of this if need be
  setup:
    steps:
    - action: torso
      params:
        height: 0.4

    - task: reset_arm
      params:
        poses: joint_poses.tuck

    - action: beep
      params:
        beep: playful
        async: true

  # Reset the arm in preparation for a new run
  reset_arm:
    params:
    - poses

    steps:
    - action: look_at_gripper
      params:
        enable: true

    - action: gripper
      params:
        command: open

    - op: make_boolean
      params:
        var_name: poses
        bool_name: poses_exist
      var:
      - poses_exist

    - action: wait
      params:
        duration: 1.0

    - action: look_at_gripper
      params:
        enable: false

    - choice: move_to_poses
      params:
        condition: var.poses_exist
        if_true:
          action: arm
          params:
            poses: params.poses
            look_at_gripper: true

  # A primitive to localize the bin on the robot's base
  localize_bin_robot:
    var:
    - bin_poses

    steps:
    - action: look
      params:
        pose: gripper_poses.kit_on_bin

    - action: beep
      params:
        beep: unsure
        async: true

    - action: wait
      params:
        duration: 1.0

    - action: detect_bins
      params:
        abort_on_zero: true
      var:
      - bin_poses

  # A primitive to pick an object from the table
  perceive:
    params:
    - object_key

    var:
    - object_idx
    - grasps

    steps:
    - action: look
      params:
        pose: gripper_poses.object_look_location

    - action: wait
      params:
        duration: 1.0

    - action: beep
      params:
        beep: surprised
        async: true

    - action: segment
      params:
        abort_on_zero: true
      var:
      - segmented_objects

    # TODO: This is where object recognition should go in
    - op: assign
      params:
        var_name: object_idx
        value: 0
      var:
      - object_idx

    - op: get_index
      params:
        var_name: segmented_objects
        idx: var.object_idx
        idx_name: segmented_obj

    - action: find_grasps
      params:
        segmented_obj: var.segmented_obj
      var:
      - grasps

  # Given the grasps and the index of the object, pick it up
  pick_task:
    params:
    - object_idx
    - grasps

    var:
    - grasped

    steps:
    - action: beep
      params:
        beep: unsure
        async: true

    - action: pick
      params:
        object_idx: params.object_idx
        grasps: params.grasps

    - action: verify_grasp
      params:
        abort_on_false: false
      var:
      - grasped

  # The combined perceive and pick task to loop over
  perceive_pick:
    params:
    - object_key

    var:
    - not_grasped

    steps:
    - action: arm
      params:
        poses: joint_poses.ready

    - task: perceive
      params:
        object_key: params.object_key
      var:
      - object_idx
      - grasps

    - task: pick_task
      params:
        object_idx: var.object_idx
        grasps: var.grasps
      var:
      - grasped

    - op: negate
      params:
        var_name: grasped
        negate_name: not_grasped
      var:
      - not_grasped

  # The loop that tries to pick until it succeeds in the perceive and pick
  perceive_pick_loop_task:
    params:
    - object_key

    steps:
    - op: assign
      params:
        var_name: not_grasped
        value: true
      var:
      - not_grasped

    - loop: perceive_pick_loop
      params:
        condition: var.not_grasped
        loop_body:
          task: perceive_pick
          params:
            object_key: params.object_key
          var:
          - not_grasped

  # A task to pick an object and stow it in the kit
  place_in_kit:
    params:
    - object_key

    steps:
    - task: perceive_pick_loop_task
      params:
        object_key: params.object_key

    - action: arm
      params:
        poses: joint_poses.ready

    - action: move_planar
      params:
        angular_amount: 3.14

    - action: move_planar
      params:
        linear_amount: 0.5

    - action: in_hand_localize
      var:
      - object_transform

    - task: localize_bin_robot
      var:
      - bin_poses

    - action: store_object
      params:
        object_key: params.object_key

    - action: beep
      params:
        beep: proud
        async: true

  # Place the bolt in the kit when the kit is on the robot
  place_bolt_in_kit:
    steps:
    - task: setup

    - action: arm
      params:
        poses: joint_poses.tuck_to_ready

    - task: place_in_kit
      params:
        object_key: BOLT

  # Place the gearbox top in the kit when the kit is on the robot
  place_gearbox_top_in_kit:
    steps:
    - task: setup

    - action: arm
      params:
        poses: joint_poses.tuck_to_ready

    - task: place_in_kit
      params:
        object_key: GEARBOX_TOP
