bool correct_object_direction
bool verify_schunk_insert
---
geometry_msgs/TransformStamped object_transform

# Error codes for in_hand_localize. If aborted the above transform is garbage
int8 SUCCESS=0
int8 ABORTED_ON_EXECUTION=-1
int8 ABORTED_ON_POSE_CHECK=-2
int8 error_code
---
