#!/usr/bin/env python
from fetchit_mapping.waypoint_map import WayPointMap
import rospy
import rospkg

log_lvls = {
   'DEBUG': rospy.DEBUG,
   'INFO': rospy.INFO,
   'WARN': rospy.WARN,
   'ERROR': rospy.ERROR,
   'FATAL': rospy.FATAL,
   'debug': rospy.DEBUG,
   'info': rospy.INFO,
   'warn': rospy.WARN,
   'error': rospy.ERROR,
   'fatal': rospy.FATAL,
}

if __name__ == "__main__":
   """
   Initialize the node
   """
   log_lvl = rospy.get_param("/logger_lvl", 'INFO')
   rospy.init_node('waypoint_publisher_node', log_level=log_lvls[log_lvl])

   # gets the roslaunch params
   rospack = rospkg.RosPack()
   map_path = rospack.get_path('fetchit_mapping')+'/maps/'
   waypoint_map_fp = rospy.get_param("waypoint_map_filepath", map_path+'arena_waypoints.yaml')

   # load map and publish
   wp_map_pub = WayPointMap(waypoint_map_fp)
   rospy.spin()
