# The different beliefs that can be updated by any node

# State of the large gear
string LARGE_GEAR_ON_TABLE=large_gear_on_table
string LARGE_GEAR_IN_SCHUNK=large_gear_in_schunk
string LARGE_GEAR_IN_KIT=large_gear_in_kit

# State of the small gear
string SMALL_GEAR_ON_TABLE=small_gear_on_table
string SMALL_GEAR_IN_KIT=small_gear_in_schunk

# State of the bolts
string ZERO_BOLTS_IN_KIT=zero_bolts_in_kit
string ONE_BOLT_IN_KIT=one_bolt_in_kit
string TWO_BOLTS_IN_KIT=two_bolts_in_kit

# State of the kit
string KIT_ON_TABLE=kit_on_table
string KIT_ON_ROBOT=kit_on_robot
string KIT_COMPLETE=kit_complete

# State of the SCHUNK
string SCHUNK_IS_MACHINING=schunk_is_machining
