waypoints:
  schunk_manipulation:
  - { x: 0.603, y: -0.112, theta: 0, frame: "map" }
  gears:
  - { x: 0.548, y: 0.111, theta: 0, frame: "map" }
  bolts:
  - { x: -0.2, y: 0.0, theta: 0, frame: "screw_bin_1" }
  gearboxes:
  - { x: 0, y: -0.4, theta: 0, frame: "kit_pick_1" }
  kits:
  - { x: -0.2, y: 0, theta: 0, frame: "kit_pick_2" }
# To establish correspondence between waypoints and semantic locations in belief, please use consistent naming here
# and in BeliefKeys.msg. BeliefKeys will be "ROBOT_AT_" + waypoint.upper().
# Also, please use location names defined in fetchit rule book.
# Correct names are provided below:
  gear_pick_station:
  - { x: -0.2, y: -0.4, theta: 0, frame: "schunk_0" }
  kit_station:
  - { x: -0.1, y: 0.1, theta: 0, frame: "kit_pick_2" }
  screw_bin_pick_station:
  - { x: -0.2, y: 0, theta: 0, frame: "screw_bin_1" }
  gearbox_pick_station:
  - { x: 0, y: 0.1, theta: 0, frame: "gearbox_pick_2"}

object_constraints: {}

arm_gripper_poses:
  object_look_location:
    frame: "base_link"
    position: { x: 0.7, y: 0.0, z: 0.7 }
    orientation: { x: 0, y: 0, z: 0, w: 1.0 }
  drop:
    frame: "base_link"
    position: { x: 0.7, y: 0.0, z: 1.0 }
    orientation: { x: 0, y: 0, z: 0, w: 1.0 }
  kit_on_bin:
    frame: "base_link"
    position: { x: 0.0, y: -0.13, z: 0.5 }
    orientation: { x: 0, y: 0, z: 0, w: 1.0 }
  neighbourhood_octomap_clear_start:
    frame: "base_link"
    position: { x: 0, y: 1.0, z: 1.0 }
    orientation: { x: 0, y: 0, z: 0, w: 1.0 }
  at_the_horizon:
    frame: "base_link"
    position: { x: 50, y: 0, z: 1.4 }
    orientation: { x: 0, y: 0, z: 0, w: 1.0 }
  at_schunk_corner:
    frame: "map"
    position: { x: 1.67, y: -0.42, z: 0.82 }
    orientation: { x: 0, y: 0, z: 0.7068252, w: 0.7073883 }

arm_joint_poses:
  tuck: [1.32, 1.47, -0.20, 1.65, 0.00, 1.66, 0.00]
  ready: [1.55, -0.91, 0.98, -1.18, 0.14, -1.06, 0.0]
  verify: [0.58, -0.94, 2.17, -1.34, -2.67, -1.54, -0.05]
  drop: [0.54, 0.06, 1.31, -1.15, 1.61, -1.68, 0.0]
  in_hand_localize: [1.13, 0.61, 1.53, -1.10, 0.22, -1.86, -0.66]
  above_schunk: [0.09128,-1.14451,2.99949,-1.13641,-3.14772,1.46717,-1.59454]

trajectories:
  tuck_to_ready:
  - [1.32, 1.47, -0.20, 1.65, 0.00, 1.66, 0.00]
  - [1.32, 1.47, -1.58, 1.65, 0.00, 1.66, 0.00]
  - [1.32, -0.46, -1.58, 1.65, 0.00, 1.66, 0.00]
  - [1.32, -0.46, -1.58, 1.65, 0.00, 0.82, 0.00]
  - [1.55, -0.91, 0.98, -1.18, 0.14, -1.06, 0.0]
  ready_to_tuck:
  - [1.55, -0.91, 0.98, -1.18, 0.14, -1.06, 0.0]
  - [1.32, -0.46, -1.58, 1.65, 0.00, 0.82, 0.00]
  - [1.32, -0.46, -1.58, 1.65, 0.00, 1.66, 0.00]
  - [1.32, 1.47, -1.58, 1.65, 0.00, 1.66, 0.00]
  - [1.32, 1.47, -0.20, 1.65, 0.00, 1.66, 0.00]

parts_at_locations:
  gear_pick_station: [SMALL_GEAR, LARGE_GEAR]
  screw_bin_pick_station: [BOLT]
  gearbox_pick_station: [GEARBOX_TOP, GEARBOX_BOTTOM]

