waypoints:
  # To establish correspondence between waypoints and semantic locations in belief,
  # please use consistent naming here and in BeliefKeys.msg. BeliefKeys will be
  # "ROBOT_AT_" + waypoint.upper().
  # Also, please use location names defined in fetchit rule book.
  # Correct names are provided below:
  gear_pick_station:
  - { x: -0.4, y: -0.2, theta: 0, frame: "schunk_0" }
  kit_station:
  - { x: -0.1, y: 0.2, theta: 0, frame: "kit_pick_1" }
  screw_bin_pick_station:
  - { x: -0.1, y: 0, theta: 0, frame: "screw_bin_1" }
  gearbox_pick_station:
  - { x: -0.1, y: -0.1, theta: 0, frame: "gearbox_pick_2"}
  # The following waypoints can be used for a retreat from one of the above
  # stations if the situation calls for it. The format here is "origin_at_" +
  # waypoint name. The values for these keys should never need to be edited
  origin_for_gear_pick_station:
  - { x: 0, y: 0, theta: 0, frame: "map" }
  origin_for_kit_station:
  - { x: 0, y: 0, theta: 1.57, frame: "map" }
  origin_for_screw_bin_pick_station:
  - { x: 0, y: 0, theta: 3.14, frame: "map" }
  origin_for_gearbox_pick_station:
  - { x: 0, y: 0, theta: -1.57, frame: "map" }

object_constraints: {}

arm_gripper_poses:
  object_look_location:
    frame: "base_link"
    position: { x: 0.7, y: 0.0, z: 0.7 }
    orientation: { x: 0, y: 0, z: 0, w: 1.0 }
  drop:
    frame: "base_link"
    position: { x: 0.7, y: 0.0, z: 1.0 }
    orientation: { x: 0, y: 0, z: 0, w: 1.0 }
  kit_on_bin:
    frame: "base_link"
    position: { x: 0.0, y: -0.13, z: 0.5 }
    orientation: { x: 0, y: 0, z: 0, w: 1.0 }
  neighbourhood_octomap_clear_start:
    frame: "base_link"
    position: { x: 0, y: 1.0, z: 1.0 }
    orientation: { x: 0, y: 0, z: 0, w: 1.0 }
  at_the_horizon:
    frame: "base_link"
    position: { x: 50, y: 0, z: 1.4 }
    orientation: { x: 0, y: 0, z: 0, w: 1.0 }

arm_joint_poses:
  tuck: [1.32, 1.47, -0.20, 1.65, 0.00, 1.66, 0.00]
  ready: [1.55, -0.91, 0.98, -1.18, 0.14, -1.06, 0.0]
  verify: [0.58, -0.94, 2.17, -1.34, -2.67, -1.54, -0.05]
  kit_drop_start: [0.38, 0.88, 2.36, -2.25, 2.66, -1.76, 2.48]
  in_hand_localize: [1.13, 0.61, 1.53, -1.10, 0.22, -1.86, -0.66]

  ready_for_candy: [1.39, -0.71, 1.56, -1.40, 0.41, -1.42, 0.69]
  pre_pick: [1.42, 0.50, 1.54, -1.83, 2.13, -1.63, 0.12]
  pick: [1.58, 0.98, 1.68, -1.34, 2.52, -1.15, 0.12]
  candy_verify_1: [1.47, 0.88, 1.80, -1.67, 0.91, -1.31, -1.53]
  candy_verify_2: [1.47, 0.88, 1.80, -1.67, 0.91, -1.31, 0.11]
  post_pick: [1.50, -0.34, 1.17, -1.42, 1.28, -1.95, -0.07]

  hat_reach_start: [1.60, -0.42, 2.72, 0.79, 0.27, 2.08, 1.38]

trajectories:
  tuck_to_ready:
  - [1.32, 1.47, -0.20, 1.65, 0.00, 1.66, 0.00]
  - [1.32, 1.47, -1.58, 1.65, 0.00, 1.66, 0.00]
  - [1.32, -0.46, -1.58, 1.65, 0.00, 1.66, 0.00]
  - [1.32, -0.46, -1.58, 1.65, 0.00, 0.82, 0.00]
  - [1.55, -0.91, 0.98, -1.18, 0.14, -1.06, 0.0]
  ready_to_tuck:
  - [1.55, -0.91, 0.98, -1.18, 0.14, -1.06, 0.0]
  - [1.32, -0.46, -1.58, 1.65, 0.00, 0.82, 0.00]
  - [1.32, -0.46, -1.58, 1.65, 0.00, 1.66, 0.00]
  - [1.32, 1.47, -1.58, 1.65, 0.00, 1.66, 0.00]
  - [1.32, 1.47, -0.20, 1.65, 0.00, 1.66, 0.00]
  kit_pick_0_to_right_place:
  - [1.56,-0.79,1.90,-2.13,2.48,-1.21,2.98]
  - [1.56,0.82,1.90,-2.13,2.48,-1.21,2.98]
  - [1.02,0.82,1.90,-2.13,2.48,-1.21,2.98]
  - [1.02,0.82,2.61,-2.24,2.93,-1.21,2.98]
  kit_pick_1_to_right_place:
  - [-1.20,-0.83,-2.88,0.70,1.67,-1.44,0.37]
  - [-1.30,-0.83,-2.88,-1.71,1.67,-0.66,0.37]
  - [-1.30,0.01,-2.88,-1.71,1.67,-0.66,0.37]
  - [-1.30,0.01,-2.88,-1.71,-0.05,-0.66,0.37]

parts_at_locations:
  gear_pick_station: [SMALL_GEAR, LARGE_GEAR]
  screw_bin_pick_station: [BOLT]
  gearbox_pick_station: [GEARBOX_TOP, GEARBOX_BOTTOM]

